# VPkg Vandor Official Repository
# Official packages from the Vandor team
version: "3.0"
repository: "https://github.com/alfariiizi/vpkg-vandor-official"
author: "Vandor Team"
license: "MIT"

# All official Vandor packages
packages:
  - name: "vandor/redis-cache"
    title: "Redis Cache"
    description: "Simple Redis adapter using go-redis/v9 with Fx integration"
    type: "fx-module"
    templates: "packages/redis-cache/templates"
    destination: "internal/vpkg/vandor/redis-cache"
    version: "v0.1.0"
    tags:
      - "full-backend"
      - "eda"
      - "minimal"
      - "cache"
    dependencies:
      - "github.com/redis/go-redis/v9"
      - "go.uber.org/fx"

  - name: "vandor/audit-logger"
    title: "Audit Logger"
    description: "Structured audit logging with context tracking"
    type: "fx-module"
    templates: "packages/audit-logger/templates"
    destination: "internal/vpkg/vandor/audit-logger"
    version: "v0.1.0"
    tags:
      - "full-backend"
      - "eda"
      - "minimal"
      - "logging"
    dependencies:
      - "go.uber.org/zap"
      - "go.uber.org/fx"

  - name: "vandor/http-huma"
    title: "Huma HTTP Server"
    description: "Huma HTTP server with OpenAPI support"
    type: "fx-module"
    templates: "packages/http-huma/templates"
    destination: "internal/vpkg/vandor/http-huma"
    version: "v0.1.0"
    tags:
      - "full-backend"
      - "minimal"
    dependencies:
      - "github.com/danielgtaylor/huma/v2"
      - "go.uber.org/fx"

