# VPkg Vandor Official Repository
# Official packages from the Vandor team
version: "3.0"
repository: "https://github.com/alfariiizi/vpkg-vandor-official"
author: "Vandor Team"
license: "MIT"

# All official Vandor packages
packages:
  - name: "vandor/redis-cache"
    title: "Redis Cache"
    description: "Simple Redis adapter using go-redis/v9 with Fx integration"
    type: "fx-module"
    templates: "packages/redis-cache/templates"
    destination: "internal/vpkg/vandor/redis-cache"
    version: "v0.1.0"
    tags:
      - "full-backend"
      - "eda"
      - "minimal"
      - "cache"
    dependencies:
      - "github.com/redis/go-redis/v9"
      - "go.uber.org/fx"

  - name: "vandor/audit-logger"
    title: "Audit Logger"
    description: "Structured audit logging with context tracking"
    type: "fx-module"
    templates: "packages/audit-logger/templates"
    destination: "internal/vpkg/vandor/audit-logger"
    version: "v0.1.0"
    tags:
      - "full-backend"
      - "eda"
      - "minimal"
      - "logging"
    dependencies:
      - "go.uber.org/zap"
      - "go.uber.org/fx"

  - name: "vandor/http-huma"
    title: "HTTP Huma Framework"
    description: "Complete HTTP delivery layer using Huma v2 with automatic route generation and Uber FX integration"
    type: "fx-module"
    templates: "packages/http-huma/templates"
    destination: "internal/vpkg/vandor/http-huma"
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "http"
      - "huma"
      - "rest"
      - "api"
      - "full-backend"
    capabilities:
      - "cli-commands"
      - "sync-integration"
      - "auto-generation"
    cli:
      entry: "cli/main.go"
      commands:
        - name: "add-route"
          description: "Add a new HTTP route handler"
          usage: "add-route <group> <name> <method>"
        - name: "add-middleware"
          description: "Add a new HTTP middleware"
          usage: "add-middleware <name>"
        - name: "sync-routes"
          description: "Regenerate route registrations"
          usage: "sync-routes"
    sync:
      provider: "sync/http_sync.go"
      commands: ["sync-routes"]
    dependencies:
      - "github.com/danielgtaylor/huma/v2"
      - "github.com/go-chi/chi/v5"
      - "go.uber.org/fx"

  - name: "vandor/sse"
    title: "Server-Sent Events Manager"
    description: "Production-ready SSE manager with topic-based subscriptions, heartbeats, and graceful shutdown for real-time web applications"
    type: "fx-module"
    templates: "packages/sse/templates"
    destination: "internal/vpkg/vandor/sse"
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "sse"
      - "real-time"
      - "events"
      - "streaming"
      - "full-backend"
    capabilities:
      - "real-time"
      - "infrastructure"
      - "cli-commands"
    cli:
      entry: "cli/main.go"
      commands:
        - name: "stats"
          description: "Show SSE manager statistics"
          usage: "stats"
        - name: "test-connection"
          description: "Test SSE endpoint connectivity"
          usage: "test-connection [endpoint]"
        - name: "monitor"
          description: "Monitor live SSE events"
          usage: "monitor [endpoint]"
        - name: "publish"
          description: "Publish an event (requires API endpoint)"
          usage: "publish <event> <data> [topic]"
    dependencies:
      - "go.uber.org/fx"

  - name: "vandor/entgo-pagination"
    title: "Entgo Pagination"
    description: "Comprehensive pagination utility for Entgo schemas with offset and cursor-based pagination, type safety, and performance optimization"
    type: "utility"
    templates: "packages/entgo-pagination/templates"
    destination: "internal/vpkg/vandor/entgo-pagination"
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "entgo"
      - "pagination"
      - "database"
      - "utilities"
      - "full-backend"
      - "eda"
      - "minimal"
    capabilities:
      - "pagination"
      - "performance"
      - "type-safety"
      - "singleton-service"
    dependencies:
      - "entgo.io/ent"
