# VPkg Vandor Official Repository
# Official packages from the Vandor team
version: "3.0"
repository: "https://github.com/alfariiizi/vpkg-vandor-official"
author: "Vandor Team"
license: "MIT"

# All official Vandor packages
packages:
  - name: "vandor/redis-cache"
    title: "Redis Cache"
    description: "Simple Redis adapter using go-redis/v9 with Fx integration"
    type: "fx-module"
    templates: "packages/redis-cache/templates"
    destination: "internal/vpkg/vandor/redis-cache"
    version: "v0.1.0"
    tags:
      - "full-backend"
      - "eda"
      - "minimal"
      - "cache"
    dependencies:
      - "github.com/redis/go-redis/v9"
      - "go.uber.org/fx"

  - name: "vandor/audit-logger"
    title: "Audit Logger"
    description: "Structured audit logging with context tracking"
    type: "fx-module"
    templates: "packages/audit-logger/templates"
    destination: "internal/vpkg/vandor/audit-logger"
    version: "v0.1.0"
    tags:
      - "full-backend"
      - "eda"
      - "minimal"
      - "logging"
    dependencies:
      - "go.uber.org/zap"
      - "go.uber.org/fx"

  - name: "vandor/http-huma"
    title: "HTTP Huma Framework"
    description: "Complete HTTP delivery layer using Huma v2 with automatic route generation and Uber FX integration"
    type: "fx-module"
    templates: "packages/http-huma/templates"
    destination: "internal/vpkg/vandor/http-huma"
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "http"
      - "huma"
      - "rest"
      - "api"
      - "full-backend"
    capabilities:
      - "cli-commands"
      - "sync-integration"
      - "auto-generation"
    cli:
      entry: "cli/main.go"
      commands:
        - name: "add-route"
          description: "Add a new HTTP route handler"
          usage: "add-route <group> <name> <method>"
        - name: "add-middleware"
          description: "Add a new HTTP middleware"
          usage: "add-middleware <name>"
        - name: "sync-routes"
          description: "Regenerate route registrations"
          usage: "sync-routes"
    sync:
      provider: "sync/http_sync.go"
      commands: ["sync-routes"]
    dependencies:
      - "github.com/danielgtaylor/huma/v2"
      - "github.com/go-chi/chi/v5"
      - "go.uber.org/fx"

  - name: "vandor/sse"
    title: "Server-Sent Events Manager"
    description: "Production-ready SSE manager with topic-based subscriptions, heartbeats, and graceful shutdown for real-time web applications"
    type: "fx-module"
    templates: "packages/sse/templates"
    destination: "internal/vpkg/vandor/sse"
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "sse"
      - "real-time"
      - "events"
      - "streaming"
      - "full-backend"
    capabilities:
      - "real-time"
      - "infrastructure"
      - "cli-commands"
    cli:
      entry: "cli/main.go"
      commands:
        - name: "stats"
          description: "Show SSE manager statistics"
          usage: "stats"
        - name: "test-connection"
          description: "Test SSE endpoint connectivity"
          usage: "test-connection [endpoint]"
        - name: "monitor"
          description: "Monitor live SSE events"
          usage: "monitor [endpoint]"
        - name: "publish"
          description: "Publish an event (requires API endpoint)"
          usage: "publish <event> <data> [topic]"
    dependencies:
      - "go.uber.org/fx"

  - name: "vandor/entgo-pagination"
    title: "Entgo Pagination"
    description: "Comprehensive pagination utility for Entgo schemas with offset and cursor-based pagination, type safety, and performance optimization"
    type: "utility"
    templates: "packages/entgo-pagination/templates"
    destination: "internal/vpkg/vandor/entgo-pagination"
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "entgo"
      - "pagination"
      - "database"
      - "utilities"
      - "full-backend"
      - "eda"
      - "minimal"
    capabilities:
      - "pagination"
      - "performance"
      - "type-safety"
      - "singleton-service"
    dependencies:
      - "entgo.io/ent"

  - name: "vandor/entgo"
    title: "Entgo Database Layer"
    description: "Complete database layer with Entgo + Entrest integration, schema management, migrations, and REST API generation"
    type: "cli-command"
    templates: "packages/entgo/templates"
    destination: "."
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "entgo"
      - "database"
      - "migrations"
      - "rest-api"
      - "code-generation"
      - "full-backend"
      - "eda"
    capabilities:
      - "cli-commands"
      - "code-generation"
      - "database-layer"
      - "rest-api"
      - "migrations"
    cli:
      entry: "cli/main.go"
      commands:
        - name: "schema new"
          description: "Create a new Entgo schema"
          usage: "schema new <SchemaName>"
        - name: "generate"
          description: "Generate Entgo + Entrest code"
          usage: "generate"
        - name: "migrate diff"
          description: "Generate migration diff"
          usage: "migrate diff <migration-name>"
        - name: "migrate up"
          description: "Apply pending migrations"
          usage: "migrate up"
        - name: "migrate status"
          description: "Check migration status"
          usage: "migrate status"
        - name: "visualize"
          description: "Generate entity relationship diagram"
          usage: "visualize"
        - name: "install-deps"
          description: "Install Entgo CLI dependencies"
          usage: "install-deps"
    dependencies:
      - "entgo.io/ent"
      - "github.com/lrstanley/entrest"
      - "github.com/hedwigz/entviz"
      - "ariga.io/atlas"
      - "github.com/google/uuid"
      - "github.com/ogen-go/ogen"
      - "github.com/lib/pq"
      - "github.com/spf13/cobra"

  - name: "vandor/cron"
    title: "Cron Scheduler System"
    description: "Complete cron job scheduling system using gocron with automatic job registration and lifecycle management"
    type: "fx-module"
    templates: "packages/cron/templates"
    destination: "internal/vpkg/vandor/cron"
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "cron"
      - "scheduler"
      - "background-jobs"
      - "full-backend"
      - "eda"
    capabilities:
      - "cli-commands"
      - "sync-integration"
      - "auto-generation"
    cli:
      entry: "cmd/cron-cli/main.go"
      commands:
        - name: "add-job"
          description: "Create a new cron job scheduler"
          usage: "add-job <name>"
        - name: "sync-jobs"
          description: "Regenerate job registry"
          usage: "sync-jobs"
    sync:
      provider: "vpkg-sync/cron_sync.go"
      commands: ["sync-jobs"]
    dependencies:
      - "github.com/go-co-op/gocron"
      - "go.uber.org/fx"

  - name: "vandor/asynq"
    title: "Asynq Background Jobs"
    description: "Complete background job processing with Asynq - job management, worker infrastructure, monitoring, and CLI commands"
    type: "cli-command"
    templates: "packages/asynq/templates"
    destination: "."
    version: "v1.0.0"
    author: "Vandor Team"
    license: "MIT"
    tags:
      - "asynq"
      - "jobs"
      - "background-processing"
      - "worker"
      - "queue"
      - "full-backend"
      - "eda"
    capabilities:
      - "cli-commands"
      - "background-jobs"
      - "job-management"
      - "worker-infrastructure"
      - "monitoring"
    cli:
      entry: "cli/main.go"
      commands:
        - name: "job new"
          description: "Create a new job handler"
          usage: "job new <JobName>"
        - name: "worker run"
          description: "Run the worker server"
          usage: "worker run"
        - name: "worker build"
          description: "Build the worker server binary"
          usage: "worker build"
        - name: "monitor"
          description: "Monitor job queues and workers"
          usage: "monitor"
        - name: "stats"
          description: "Show queue statistics"
          usage: "stats"
        - name: "install-deps"
          description: "Install Asynq CLI dependencies"
          usage: "install-deps"
    dependencies:
      - "github.com/hibiken/asynq"
      - "github.com/redis/go-redis/v9"
      - "go.uber.org/fx"
      - "go.uber.org/zap"
      - "github.com/spf13/cobra"
